image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

flake8:
  stage: test
  image: python:3.7-alpine
  before_script:
    - pip install -r requirements.txt

  script:
    - flake8 maildown

mypy:
  stage: test
  image: python:3.7-alpine
  before_script:
    - pip install -r requirements.txt
  script:
    - mypy maildown --ignore-missing-imports
