image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

flake8:
  stage: test
  image: python:3.7-alpine
  before_script:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - poetry install

  script:
    - flake8 maildown

mypy:
  stage: test
  image: python:3.7-alpine
  before_script:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - poetry install
  script:
    - mypy maildown --ignore-missing-imports
