image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

flake8:
  stage: test
  before_script:
    - pip3 install -r requirements.txt

  script:
    - flake8 maildown


mypy:
  stage: test
  before_script:
    - pip3 install -r requirements.txt
  script:
    - mypy maildown --ignore-missing-imports
