language: python

python:
  - "3.7"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install pytest-cov==2.7.1
  - poetry install

script:
  - mypy maildown --ignore-missing-imports
  - flake8 maildown
  - poetry run pytest tests --cov=maildown
  - coverage report --fail-under=95

after_success:
  - coveralls

before_deploy:
  - poetry config http-basic.pypi chris140957 $PYPI_PASSWORD

deploy:
  - provider: script
    script: poetry publish --build
    on:
      tags: true
      branch: master